name: 'Deploy Multiple Subdomains/Projects to Firebase'
author: 'Clement Oh <clement.oh094@gmail.com>'
description: 'A GitHub Action to deploy multiple subdomains to Firebase Hosting'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'
